INSERT INTO `st_setup_gl` VALUES ('1', null, null, null, null, null, '电子商城', '电子商城', '电子商城', '<p>CopyRight &copy;️ 2025 电子商城 All Rights&nbsp;</p>', '', '', '', '', '', '', '', '深圳市森蓝微电子有限公司', '联系我们：0755-21082640\r\n客服QQ：3007726439\r\n地址：深圳市龙华新区民宝路淘景大厦12楼', '深圳市龙华新区民宝路淘景大厦12楼', '[89]', '[89]', '114.02975462521175,22.623197598865033', 'zh-cn', null);



INSERT INTO `st_master_menu` VALUES ('1', '1', '0', '网站设置', '', null, null, 'layui-icon-set-sm', 'zh-cn', null, '1', '0', null, null);
INSERT INTO `st_master_menu` VALUES ('2', '2', '1', '系统设置', 'SetupGl/setconfig', null, null, 'layui-icon-set-fill', 'zh-cn', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('3', '1', '1', '网站基本设置', 'setupGl/edit', '', '', null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('4', '1', '1', '图片批量上传', 'pl_dao/pl_imru_tool/add', '', '', null, 'zh-cn', null, '0', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('5', '1', '1', '数据批量导入', 'pl_dao/pl_daru_tool/add', '', '', null, 'zh-cn', null, '0', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('6', '1', '1', '数据批量导出', 'pl_dao/pl_dacu_tool/add', '', '', null, 'zh-cn', null, '0', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('7', '1', '1', '关键词管理', 'key_co/default', '', '', null, 'zh-cn', null, '1', '6', null, null);
INSERT INTO `st_master_menu` VALUES ('8', '1', '1', 'CRUD', 'setupGl/crud', '', '', null, 'zh-cn', null, '1', '7', null, null);
INSERT INTO `st_master_menu` VALUES ('301', '1', '0', '首页管理', '', null, null, 'layui-icon-home', 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('302', '2', '301', '系统设置', 'HomeLm/setconfig', null, null, null, 'zh-cn', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('303', '3', '301', 'SEO设置', 'SetupSy/edit?sy_id=2', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('304', '1', '301', '首页分类管理', 'HomeLm/default', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('305', '1', '301', '首页信息管理', 'HomeCo/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('306', '1', '0', '产品管理', '', null, null, 'layui-icon-component', 'zh-cn', null, '1', '8', null, null);
INSERT INTO `st_master_menu` VALUES ('307', '2', '306', '系统设置', 'ProLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('308', '3', '306', 'seo设置', 'SetupSy/edit?sy_id=3', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('309', '1', '306', '产品分类管理', 'ProLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('310', '1', '306', '产品信息管理', 'ProCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('318', '3', '316', 'seo设置', 'SetupSy/edit?sy_id=4', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('317', '2', '316', '系统设置', 'BrandLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('316', '1', '0', '品牌管理', '', null, null, 'layui-icon-app', 'zh-cn', null, '1', '7', null, null);
INSERT INTO `st_master_menu` VALUES ('319', '1', '316', '品牌分类管理', 'BrandLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('320', '1', '316', '品牌信息管理', 'BrandCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('321', '1', '0', '新闻管理', '', null, null, 'layui-icon-form', 'zh-cn', null, '1', '9', null, null);
INSERT INTO `st_master_menu` VALUES ('322', '2', '321', '系统设置', 'NewsLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('323', '3', '321', 'seo设置', 'SetupSy/edit?sy_id=5', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('324', '1', '321', '新闻分类管理', 'NewsLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('325', '1', '321', '新闻信息管理', 'NewsCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('326', '1', '0', '参数管理', '', null, null, 'layui-icon-slider', 'zh-cn', null, '1', '10', null, null);
INSERT INTO `st_master_menu` VALUES ('327', '2', '326', '系统设置', 'ParamLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('328', '3', '326', 'seo设置', 'SetupSy/edit?sy_id=6', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('329', '1', '326', '参数分类管理', 'ParamLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('330', '1', '326', '参数信息管理', 'ParamCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('331', '1', '0', '网站管理', '', null, null, 'layui-icon-website', 'zh-cn', null, '1', '11', null, null);
INSERT INTO `st_master_menu` VALUES ('332', '2', '331', '系统设置', 'WebLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('333', '3', '331', 'seo设置', 'SetupSy/edit?sy_id=7', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('334', '1', '331', '网站分类管理', 'WebLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('335', '1', '331', '网站信息管理', 'WebCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('336', '1', '0', '文章管理', '', null, null, 'layui-icon-read', 'zh-cn', null, '1', '12', null, null);
INSERT INTO `st_master_menu` VALUES ('337', '2', '336', '系统设置', 'ArticleLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('338', '3', '336', 'seo设置', 'SetupSy/edit?sy_id=8', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('339', '1', '336', '文章分类管理', 'ArticleLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('340', '1', '336', '文章信息管理', 'ArticleCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('341', '1', '0', '投喂管理', '', null, null, 'layui-icon-date', 'zh-cn', null, '1', '13', null, null);
INSERT INTO `st_master_menu` VALUES ('342', '2', '341', '系统设置', 'FeedLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('343', '3', '341', 'seo设置', 'SetupSy/edit?sy_id=9', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('344', '1', '341', '投喂分类管理', 'FeedLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('345', '1', '341', '投喂信息管理', 'FeedCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('346', '1', '341', '投喂记录', 'FeedCo/record', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('359', '1', '357', 'Basic website settings', 'setupGl/edit', '', '', null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('358', '2', '357', 'System Settings', 'SetupGl/setconfig', null, null, 'layui-icon-set-fill', 'en', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('357', '1', '0', 'Website Settings', '', null, null, 'layui-icon-set-sm', 'en', null, '1', '0', null, null);
INSERT INTO `st_master_menu` VALUES ('352', '1', '0', 'Icon管理', '', null, null, 'layui-icon-picture-fine', 'zh-cn', null, '1', '6', null, null);
INSERT INTO `st_master_menu` VALUES ('353', '2', '352', '系统设置', 'IconLm/setconfig', null, null, null, 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('354', '3', '352', 'seo设置', 'SetupSy/edit?sy_id=23', null, null, null, 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('355', '1', '352', 'Icon分类管理', 'IconLm/default', null, null, null, 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('356', '1', '352', 'Icon信息管理', 'IconCo/default', null, null, null, 'zh-cn', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('360', '1', '357', 'Batch upload of images', 'pl_dao/pl_imru_tool/add', '', '', null, 'en', null, '0', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('361', '1', '357', 'Batch import of data', 'pl_dao/pl_daru_tool/add', '', '', null, 'en', null, '0', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('362', '1', '357', 'Batch export of data', 'pl_dao/pl_dacu_tool/add', '', '', null, 'en', null, '0', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('363', '1', '357', 'keyword management', 'key_co/default', '', '', null, 'en', null, '1', '6', null, null);
INSERT INTO `st_master_menu` VALUES ('364', '1', '357', 'CRUD', 'setupGl/crud', '', '', null, 'en', null, '1', '7', null, null);
INSERT INTO `st_master_menu` VALUES ('365', '1', '0', 'Homepage Management', '', null, null, 'layui-icon-home', 'en', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('366', '2', '365', 'System Settings', 'HomeLm/setconfig', null, null, null, 'en', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('367', '3', '365', 'SEO Settings', 'SetupSy/edit?sy_id=2', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('368', '1', '365', 'Home Category Management', 'HomeLm/default', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('369', '1', '365', 'Home Information Management', 'HomeCo/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('370', '1', '0', 'Product Management', '', null, null, 'layui-icon-component', 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('371', '2', '370', 'System Settings', 'ProLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('372', '3', '370', 'SEO Settings', 'SetupSy/edit?sy_id=3', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('373', '1', '370', 'Product classification management', 'ProLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('374', '1', '370', 'Product Information Management', 'ProCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('375', '3', '377', 'SEO Settings', 'SetupSy/edit?sy_id=4', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('376', '2', '377', 'System Settings', 'BrandLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('377', '1', '0', 'Brand Management', '', null, null, 'layui-icon-app', 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('378', '1', '377', 'Brand classification management', 'BrandLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('379', '1', '377', 'Brand Information Management', 'BrandCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('380', '1', '0', 'News Management', '', null, null, 'layui-icon-form', 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('381', '2', '380', 'System Settings', 'NewsLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('382', '3', '380', 'SEO Settings', 'SetupSy/edit?sy_id=5', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('383', '1', '380', 'News classification management', 'NewsLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('384', '1', '380', 'News Information Management', 'NewsCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('385', '1', '0', 'parameter management', '', null, null, 'layui-icon-slider', 'en', null, '1', '6', null, null);
INSERT INTO `st_master_menu` VALUES ('386', '2', '385', 'System Settings', 'ParamLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('387', '3', '385', 'SEO Settings', 'SetupSy/edit?sy_id=6', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('388', '1', '385', 'Parameter classification management', 'ParamLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('389', '1', '385', 'Parameter information management', 'ParamCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('390', '1', '0', 'Website Management', '', null, null, 'layui-icon-website', 'en', null, '1', '7', null, null);
INSERT INTO `st_master_menu` VALUES ('391', '2', '390', 'System Settings', 'WebLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('392', '3', '390', 'SEO Settings', 'SetupSy/edit?sy_id=7', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('393', '1', '390', 'Website classification management', 'WebLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('394', '1', '390', 'Website Information Management', 'WebCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('395', '1', '0', 'Article Management', '', null, null, 'layui-icon-read', 'en', null, '1', '8', null, null);
INSERT INTO `st_master_menu` VALUES ('396', '2', '395', 'System Settings', 'ArticleLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('397', '3', '395', 'SEO Settings', 'SetupSy/edit?sy_id=8', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('398', '1', '395', 'Article classification management', 'ArticleLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('399', '1', '395', 'Article Information Management', 'ArticleCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('400', '1', '0', 'Feeding management', '', null, null, 'layui-icon-date', 'en', null, '1', '9', null, null);
INSERT INTO `st_master_menu` VALUES ('401', '2', '400', 'System Settings', 'FeedLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('402', '3', '400', 'SEO Settings', 'SetupSy/edit?sy_id=9', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('403', '1', '400', 'Feeding classification management', 'FeedLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('404', '1', '400', 'Feeding information management', 'FeedCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('405', '1', '400', 'Feeding record', 'FeedCo/record', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('406', '1', '0', 'Icon Management', '', null, null, 'layui-icon-picture-fine', 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('407', '2', '406', 'System Settings', 'IconLm/setconfig', null, null, null, 'en', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('408', '3', '406', 'SEO Settings', 'SetupSy/edit?sy_id=23', null, null, null, 'en', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('409', '1', '406', 'Icon classification management', 'IconLm/default', null, null, null, 'en', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('410', '1', '406', 'Icon Information Management', 'IconCo/default', null, null, null, 'en', null, '1', '5', null, null);
INSERT INTO `st_master_menu` VALUES ('411', '1', '0', '管理员管理', '', null, null, 'layui-icon-username', 'zh-cn', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('412', '2', '411', '系统设置', 'Master/setconfig', null, null, 'layui-icon-set-sm', 'zh-cn', null, '1', '1', null, '2025-11-22 11:18:14');
INSERT INTO `st_master_menu` VALUES ('413', '1', '411', '管理员管理', 'Master/default', null, null, 'layui-icon-friends', 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('414', '1', '0', '订单管理', '', null, null, 'layui-icon-list', 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('415', '2', '414', '系统设置', 'Order/setconfig', null, null, 'layui-icon-set-fill', 'zh-cn', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('416', '1', '414', '订单信息管理', 'Order/default', null, null, 'layui-icon-cols', 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('417', '1', '411', '查看操作日志', 'Master/default_log', null, null, 'layui-icon-menu-fill', 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('418', '1', '0', '会员管理', '', null, null, 'layui-icon-user', 'zh-cn', null, '1', '3', null, null);
INSERT INTO `st_master_menu` VALUES ('419', '2', '418', '系统设置', 'Person/Setconfig', null, null, 'layui-icon-set-fill', 'zh-cn', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('420', '1', '418', '会员信息管理', 'Person/Default', null, null, 'layui-icon-friends', 'zh-cn', null, '1', '2', null, null);
INSERT INTO `st_master_menu` VALUES ('421', '1', '0', '留言管理', '', null, null, 'layui-icon-form', 'zh-cn', null, '1', '4', null, null);
INSERT INTO `st_master_menu` VALUES ('422', '2', '421', '系统设置', 'Book/setconfig', null, null, 'layui-icon-set-fill', 'zh-cn', null, '1', '1', null, null);
INSERT INTO `st_master_menu` VALUES ('423', '1', '421', '留言信息管理', 'Book/default', null, null, 'layui-icon-form', 'zh-cn', null, '1', '2', null, null);




INSERT INTO `st_master_action` VALUES ('336', '411', '添加管理员', 'Master_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('337', '411', '删除管理员', 'Master_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('338', '411', '编辑管理员', 'Master_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('339', '411', '查看管理员', 'Master_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('340', '411', '查看管理员日志', 'Master_log_default', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('383', '1', '批量设置', 'PlDao_*', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('432', '52', '留言回收站', 'book_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('282', '52', '留言回复', 'Book_huifu', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('283', '52', '删除留言', 'Book_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('284', '52', '编辑留言', 'Book_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('285', '52', '查看留言', 'Book_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('208', '1', '添加关键词', 'KeyCo_add', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('209', '1', '删除关键词', 'KeyCo_del', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('210', '1', '编辑关键词', 'KeyCo_edit', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('211', '1', '查看关键词', 'KeyCo_default', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('438', '90', '管理员回收', 'Master_recycle', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('227', '1', '编辑网站设置', 'SetupGl_edit', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('690', '306', '添加分类', 'ProLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('691', '306', '删除分类', 'ProLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('692', '306', '编辑分类', 'ProLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('693', '306', '查看分类', 'ProLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('694', '306', '分类回收站', 'ProLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('695', '306', '添加信息', 'ProCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('696', '306', '删除信息', 'ProCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('697', '306', '编辑信息', 'ProCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('698', '306', '查看信息', 'ProCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('699', '306', '信息回收站', 'ProCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('717', '316', '编辑信息', 'BrandCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('716', '316', '删除信息', 'BrandCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('715', '316', '添加信息', 'BrandCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('714', '316', '分类回收站', 'BrandLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('713', '316', '查看分类', 'BrandLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('712', '316', '编辑分类', 'BrandLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('711', '316', '删除分类', 'BrandLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('710', '316', '添加分类', 'BrandLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('718', '316', '查看信息', 'BrandCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('719', '316', '信息回收站', 'BrandCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('720', '321', '添加分类', 'NewsLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('721', '321', '删除分类', 'NewsLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('722', '321', '编辑分类', 'NewsLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('723', '321', '查看分类', 'NewsLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('724', '321', '分类回收站', 'NewsLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('725', '321', '添加信息', 'NewsCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('726', '321', '删除信息', 'NewsCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('727', '321', '编辑信息', 'NewsCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('728', '321', '查看信息', 'NewsCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('729', '321', '信息回收站', 'NewsCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('730', '326', '添加分类', 'ParamLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('731', '326', '删除分类', 'ParamLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('732', '326', '编辑分类', 'ParamLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('733', '326', '查看分类', 'ParamLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('734', '326', '分类回收站', 'ParamLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('735', '326', '添加信息', 'ParamCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('736', '326', '删除信息', 'ParamCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('737', '326', '编辑信息', 'ParamCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('738', '326', '查看信息', 'ParamCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('739', '326', '信息回收站', 'ParamCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('740', '331', '添加分类', 'WebLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('741', '331', '删除分类', 'WebLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('742', '331', '编辑分类', 'WebLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('743', '331', '查看分类', 'WebLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('744', '331', '分类回收站', 'WebLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('745', '331', '添加信息', 'WebCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('746', '331', '删除信息', 'WebCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('747', '331', '编辑信息', 'WebCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('748', '331', '查看信息', 'WebCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('749', '331', '信息回收站', 'WebCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('750', '336', '添加信息', 'ArticleCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('751', '336', '删除信息', 'ArticleCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('752', '336', '编辑信息', 'ArticleCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('753', '336', '查看信息', 'ArticleCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('754', '336', '信息回收站', 'ArticleCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('755', '336', '添加分类', 'ArticleLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('756', '336', '删除分类', 'ArticleLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('757', '336', '编辑分类', 'ArticleLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('758', '336', '查看分类', 'ArticleLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('759', '336', '分类回收站', 'ArticleLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('760', '341', '添加分类', 'FeedLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('761', '341', '删除分类', 'FeedLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('762', '341', '编辑分类', 'FeedLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('763', '341', '查看分类', 'FeedLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('764', '341', '分类回收站', 'FeedLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('765', '341', '添加信息', 'FeedCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('766', '341', '删除信息', 'FeedCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('767', '341', '编辑信息', 'FeedCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('768', '341', '查看信息', 'FeedCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('769', '341', '信息回收站', 'FeedCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('770', '301', '添加分类', 'HomeLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('771', '301', '删除分类', 'HomeLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('772', '301', '编辑分类', 'HomeLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('773', '301', '查看分类', 'HomeLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('774', '301', '分类回收站', 'HomeLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('775', '301', '添加信息', 'HomeCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('776', '301', '删除信息', 'HomeCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('777', '301', '编辑信息', 'HomeCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('778', '301', '查看信息', 'HomeCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('779', '301', '信息回收站', 'HomeCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('808', '52', 'Reply to comments', 'Book_huifu', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('807', '52', 'Recycle Bin', 'book_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('806', '1', 'Batch Settings', 'PlDao_*', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('805', '90', 'View operation logs', 'Master_log_default', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('804', '90', 'View Administrator', 'Master_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('803', '90', 'Modify Administrator', 'Master_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('802', '90', 'Delete Administrator', 'Master_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('801', '90', 'Add Administrator', 'Master_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('790', '352', '添加分类', 'IconLm_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('791', '352', '删除分类', 'IconLm_del', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('792', '352', '编辑分类', 'IconLm_edit', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('793', '352', '查看分类', 'IconLm_default', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('794', '352', '分类回收站', 'IconLm_recycle', 'zh-cn', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('795', '352', '添加信息', 'IconCo_add', 'zh-cn', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('796', '352', '删除信息', 'IconCo_del', 'zh-cn', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('797', '352', '编辑信息', 'IconCo_edit', 'zh-cn', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('798', '352', '查看信息', 'IconCo_default', 'zh-cn', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('799', '352', '信息回收站', 'IconCo_recycle', 'zh-cn', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('809', '52', 'Delete message', 'Book_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('810', '52', 'Modify message', 'Book_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('811', '52', 'View messages', 'Book_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('812', '1', 'Add keywords', 'KeyCo_add', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('813', '1', 'Delete keywords', 'KeyCo_del', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('814', '1', 'Modify keywords', 'KeyCo_edit', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('815', '1', 'View keywords', 'KeyCo_default', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('816', '90', 'Recycle Bin', 'Master_recycle', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('817', '1', 'Basic website settings', 'SetupGl_edit', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('818', '306', 'Add category', 'ProLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('819', '306', 'Delete category', 'ProLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('820', '306', 'Change classification', 'ProLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('821', '306', 'View categories', 'ProLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('822', '306', 'Classification Recycle Bin', 'ProLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('823', '306', 'Add information', 'ProCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('824', '306', 'Delete information', 'ProCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('825', '306', 'Modify information', 'ProCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('826', '306', 'View information', 'ProCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('827', '306', 'Information Recycle Bin', 'ProCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('828', '316', 'Modify information', 'BrandCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('829', '316', 'Delete information', 'BrandCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('830', '316', 'Add information', 'BrandCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('831', '316', 'Classification Recycle Bin', 'BrandLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('832', '316', 'View categories', 'BrandLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('833', '316', 'Change classification', 'BrandLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('834', '316', 'Delete category', 'BrandLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('835', '316', 'Add category', 'BrandLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('836', '316', 'View information', 'BrandCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('837', '316', 'Information Recycle Bin', 'BrandCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('838', '321', 'Add category', 'NewsLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('839', '321', 'Delete category', 'NewsLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('840', '321', 'Change classification', 'NewsLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('841', '321', 'View categories', 'NewsLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('842', '321', 'Classification Recycle Bin', 'NewsLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('843', '321', 'Add information', 'NewsCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('844', '321', 'Delete information', 'NewsCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('845', '321', 'Modify information', 'NewsCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('846', '321', 'View information', 'NewsCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('847', '321', 'Information Recycle Bin', 'NewsCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('848', '326', 'Add category', 'ParamLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('849', '326', 'Delete category', 'ParamLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('850', '326', 'Change classification', 'ParamLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('851', '326', 'View categories', 'ParamLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('852', '326', 'Classification Recycle Bin', 'ParamLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('853', '326', 'Add information', 'ParamCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('854', '326', 'Delete information', 'ParamCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('855', '326', 'Modify information', 'ParamCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('856', '326', 'View information', 'ParamCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('857', '326', 'Information Recycle Bin', 'ParamCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('858', '331', 'Add category', 'WebLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('859', '331', 'Delete category', 'WebLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('860', '331', 'Change classification', 'WebLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('861', '331', 'View categories', 'WebLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('862', '331', 'Classification Recycle Bin', 'WebLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('863', '331', 'Add information', 'WebCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('864', '331', 'Delete information', 'WebCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('865', '331', 'Modify information', 'WebCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('866', '331', 'View information', 'WebCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('867', '331', 'Information Recycle Bin', 'WebCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('868', '336', 'Add category', 'ArticleCo_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('869', '336', 'Delete category', 'ArticleCo_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('870', '336', 'Change classification', 'ArticleCo_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('871', '336', 'View categories', 'ArticleCo_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('872', '336', 'Classification Recycle Bin', 'ArticleCo_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('873', '336', 'Add information', 'ArticleLm_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('874', '336', 'Delete information', 'ArticleLm_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('875', '336', 'Modify information', 'ArticleLm_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('876', '336', 'View information', 'ArticleLm_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('877', '336', 'Information Recycle Bin', 'ArticleLm_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('878', '341', 'Add category', 'FeedLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('879', '341', 'Delete category', 'FeedLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('880', '341', 'Change classification', 'FeedLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('881', '341', 'View categories', 'FeedLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('882', '341', 'Classification Recycle Bin', 'FeedLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('883', '341', 'Add information', 'FeedCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('884', '341', 'Delete information', 'FeedCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('885', '341', 'Modify information', 'FeedCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('886', '341', 'View information', 'FeedCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('887', '341', 'Information Recycle Bin', 'FeedCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('888', '301', 'Add category', 'HomeLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('889', '301', 'Delete category', 'HomeLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('890', '301', 'Change classification', 'HomeLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('891', '301', 'View categories', 'HomeLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('892', '301', 'Classification Recycle Bin', 'HomeLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('893', '301', 'Add information', 'HomeCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('894', '301', 'Delete information', 'HomeCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('895', '301', 'Modify information', 'HomeCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('896', '301', 'View information', 'HomeCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('897', '301', 'Information Recycle Bin', 'HomeCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('898', '352', 'Add category', 'IconLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('899', '352', 'Delete category', 'IconLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('900', '352', 'Change classification', 'IconLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('901', '352', 'View categories', 'IconLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('902', '352', 'Classification Recycle Bin', 'IconLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('903', '352', 'Add information', 'IconCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('904', '352', 'Delete information', 'IconCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('905', '352', 'Modify information', 'IconCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('906', '352', 'View information', 'IconCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('907', '352', 'Information Recycle Bin', 'IconCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('1022', '418', '添加会员', 'Person_add', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('1021', '414', '信息回收站', 'Order_recycle', 'zh-cn', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('1020', '414', '查看信息', 'Order_default', 'zh-cn', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('1019', '414', '编辑信息', 'Order_edit', 'zh-cn', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('1018', '414', '删除信息', 'Order_del', 'zh-cn', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('908', '52', 'Reply to comments', 'Book_huifu', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('909', '52', 'Reply to comments', 'Book_huifu', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('910', '52', 'Recycle Bin', 'book_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('911', '1', 'Batch Settings', 'PlDao_*', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('912', '90', 'View operation logs', 'Master_log_default', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('913', '90', 'View Administrator', 'Master_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('914', '90', 'Modify Administrator', 'Master_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('915', '90', 'Delete Administrator', 'Master_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('916', '90', 'Add Administrator', 'Master_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('1017', '341', '查看记录', 'FeedCo_record', 'zh-cn', '', '1', '11', null, null);
INSERT INTO `st_master_action` VALUES ('917', '52', 'Delete message', 'Book_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('918', '52', 'Modify message', 'Book_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('919', '52', 'View messages', 'Book_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('920', '1', 'Add keywords', 'KeyCo_add', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('921', '1', 'Delete keywords', 'KeyCo_del', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('922', '1', 'Modify keywords', 'KeyCo_edit', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('923', '1', 'View keywords', 'KeyCo_default', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('924', '90', 'Recycle Bin', 'Master_recycle', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('925', '1', 'Basic website settings', 'SetupGl_edit', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('926', '306', 'Add category', 'ProLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('927', '306', 'Delete category', 'ProLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('928', '306', 'Change classification', 'ProLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('929', '306', 'View categories', 'ProLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('930', '306', 'Classification Recycle Bin', 'ProLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('931', '306', 'Add information', 'ProCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('932', '306', 'Delete information', 'ProCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('933', '306', 'Modify information', 'ProCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('934', '306', 'View information', 'ProCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('935', '306', 'Information Recycle Bin', 'ProCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('936', '316', 'Modify information', 'BrandCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('937', '316', 'Delete information', 'BrandCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('938', '316', 'Add information', 'BrandCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('939', '316', 'Classification Recycle Bin', 'BrandLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('940', '316', 'View categories', 'BrandLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('941', '316', 'Change classification', 'BrandLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('942', '316', 'Delete category', 'BrandLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('943', '316', 'Add category', 'BrandLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('944', '316', 'View information', 'BrandCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('945', '316', 'Information Recycle Bin', 'BrandCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('946', '321', 'Add category', 'NewsLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('947', '321', 'Delete category', 'NewsLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('948', '321', 'Change classification', 'NewsLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('949', '321', 'View categories', 'NewsLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('950', '321', 'Classification Recycle Bin', 'NewsLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('951', '321', 'Add information', 'NewsCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('952', '321', 'Delete information', 'NewsCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('953', '321', 'Modify information', 'NewsCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('954', '321', 'View information', 'NewsCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('955', '321', 'Information Recycle Bin', 'NewsCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('956', '326', 'Add category', 'ParamLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('957', '326', 'Delete category', 'ParamLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('958', '326', 'Change classification', 'ParamLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('959', '326', 'View categories', 'ParamLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('960', '326', 'Classification Recycle Bin', 'ParamLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('961', '326', 'Add information', 'ParamCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('962', '326', 'Delete information', 'ParamCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('963', '326', 'Modify information', 'ParamCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('964', '326', 'View information', 'ParamCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('965', '326', 'Information Recycle Bin', 'ParamCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('966', '331', 'Add category', 'WebLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('967', '331', 'Delete category', 'WebLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('968', '331', 'Change classification', 'WebLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('969', '331', 'View categories', 'WebLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('970', '331', 'Classification Recycle Bin', 'WebLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('971', '331', 'Add information', 'WebCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('972', '331', 'Delete information', 'WebCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('973', '331', 'Modify information', 'WebCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('974', '331', 'View information', 'WebCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('975', '331', 'Information Recycle Bin', 'WebCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('976', '336', 'Add category', 'ArticleCo_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('977', '336', 'Delete category', 'ArticleCo_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('978', '336', 'Change classification', 'ArticleCo_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('979', '336', 'View categories', 'ArticleCo_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('980', '336', 'Classification Recycle Bin', 'ArticleCo_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('981', '336', 'Add information', 'ArticleLm_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('982', '336', 'Delete information', 'ArticleLm_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('983', '336', 'Modify information', 'ArticleLm_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('984', '336', 'View information', 'ArticleLm_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('985', '336', 'Information Recycle Bin', 'ArticleLm_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('986', '341', 'Add category', 'FeedLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('987', '341', 'Delete category', 'FeedLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('988', '341', 'Change classification', 'FeedLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('989', '341', 'View categories', 'FeedLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('990', '341', 'Classification Recycle Bin', 'FeedLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('991', '341', 'Add information', 'FeedCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('992', '341', 'Delete information', 'FeedCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('993', '341', 'Modify information', 'FeedCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('994', '341', 'View information', 'FeedCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('995', '341', 'Information Recycle Bin', 'FeedCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('996', '301', 'Add category', 'HomeLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('997', '301', 'Delete category', 'HomeLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('998', '301', 'Change classification', 'HomeLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('999', '301', 'View categories', 'HomeLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('1000', '301', 'Classification Recycle Bin', 'HomeLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('1001', '301', 'Add information', 'HomeCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('1002', '301', 'Delete information', 'HomeCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('1003', '301', 'Modify information', 'HomeCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('1004', '301', 'View information', 'HomeCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('1005', '301', 'Information Recycle Bin', 'HomeCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('1006', '352', 'Add category', 'IconLm_add', 'en', '', '1', '1', null, null);
INSERT INTO `st_master_action` VALUES ('1007', '352', 'Delete category', 'IconLm_del', 'en', '', '1', '2', null, null);
INSERT INTO `st_master_action` VALUES ('1008', '352', 'Change classification', 'IconLm_edit', 'en', '', '1', '3', null, null);
INSERT INTO `st_master_action` VALUES ('1009', '352', 'View categories', 'IconLm_default', 'en', '', '1', '4', null, null);
INSERT INTO `st_master_action` VALUES ('1010', '352', 'Classification Recycle Bin', 'IconLm_recycle', 'en', '', '1', '5', null, null);
INSERT INTO `st_master_action` VALUES ('1011', '352', 'Add information', 'IconCo_add', 'en', '', '1', '6', null, null);
INSERT INTO `st_master_action` VALUES ('1012', '352', 'Delete information', 'IconCo_del', 'en', '', '1', '7', null, null);
INSERT INTO `st_master_action` VALUES ('1013', '352', 'Modify information', 'IconCo_edit', 'en', '', '1', '8', null, null);
INSERT INTO `st_master_action` VALUES ('1014', '352', 'View information', 'IconCo_default', 'en', '', '1', '9', null, null);
INSERT INTO `st_master_action` VALUES ('1015', '352', 'Information Recycle Bin', 'IconCo_recycle', 'en', '', '1', '10', null, null);
INSERT INTO `st_master_action` VALUES ('1016', '52', 'Reply to comments', 'Book_huifu', 'en', '', '1', '1', null, null);
